version: '3.9'
services:
  nexus:
    image: sonatype/nexus3:3.37.3
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
  jenkins:
    image: jenkinsci/blueocean:1.25.3
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube-data:/opt/sonarqube/data
      - ./sonarqube-logs:/opt/sonarqube/logs
